
baseURL = "https://adityakadoo.github.io/Scrolls/" # website root path
languageCode = "en-us"                       # content language
theme = ""               # theme directory name
title = "Scrolls"                          # website title

[author]
email = "aditya1449kadoo@gmail.com" # your email
name = "Aditya Kadoo"          # your name

# https://gohugo.io/getting-started/configuration-markup
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true # enable html in markdown
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = true
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'algol_nu'
tabWidth = 2 # syntax highlight style, see https://xyproto.github.io/splash/docs/
[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[params]
description = "an example site for hugo theme TeXify" # website description
favicon = "favicon.ico" # path to website icon, relative to ./static
footnote = """
Follow me on <a class=link href=https://github.com/adityakadoo>GitHub</a> |
<a class=link href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh target=_blank rel=noopener>CC BY-NC-SA 4.0</a>
""" # notes in the website footer

customCSS = ["css/syntax.css"]            # path to custom css files, relative to ./static
customJS = []             # path to custom js files, relative to ./static
dateFormat = "2006-01-02" # date format, see https://gohugo.io/functions/format/
since = "2022"            # website created year
toc = false               # whether to enable table of contents in posts

[params.math]
enable = false # whether to enable math typesetting
use = "katex"  # katex or mathjax
